// src/app/runs/page.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import Navbar from '@/components/Navbar';
import RunCard from '@/components/RunCard';

interface Run {
  _id: string;
  actorId: string;
  actorName: string;
  status: 'pending' | 'queued' | 'running' | 'succeeded' | 'failed' | 'timed-out' | 'aborted';
  input: Record<string, unknown>;
  output?: { resultsCount: number; previewResults: unknown[] };
  stats: { startedAt?: string; finishedAt?: string; durationMs?: number };
  createdAt: string;
}

const STATUS_FILTERS = [
  { id: '', label: 'All', count: null },
  { id: 'running', label: 'Running', icon: '⚡' },
  { id: 'succeeded', label: 'Succeeded', icon: '✅' },
  { id: 'failed', label: 'Failed', icon: '❌' },
  { id: 'pending', label: 'Pending', icon: '⏳' },
];

export default function RunsPage() {
  const [runs, setRuns] = useState<Run[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState('');
  const [pagination, setPagination] = useState({ page: 1, total: 0, totalPages: 1 });
  const [autoRefresh, setAutoRefresh] = useState(true);

  const fetchRuns = useCallback(async (page = 1) => {
    try {
      const params = new URLSearchParams({ page: String(page), limit: '10' });
      if (statusFilter) params.set('status', statusFilter);
      const res = await fetch(`/api/runs?${params}`);
      const data = await res.json();
      setRuns(data.runs || []);
      setPagination(data.pagination || { page: 1, total: 0, totalPages: 1 });
    } catch (err) {
      console.error('Failed to fetch runs:', err);
    } finally {
      setLoading(false);
    }
  }, [statusFilter]);

  useEffect(() => {
    setLoading(true);
    fetchRuns(1);
  }, [fetchRuns]);

  useEffect(() => {
    if (!autoRefresh) return;
    const interval = setInterval(() => fetchRuns(pagination.page), 5000);
    return () => clearInterval(interval);
  }, [autoRefresh, fetchRuns, pagination.page]);

  const handleAbort = async (id: string) => {
    try {
      await fetch(`/api/runs/${id}`, { method: 'DELETE' });
      fetchRuns(pagination.page);
    } catch (err) {
      console.error('Abort failed:', err);
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await fetch(`/api/runs/${id}`, { method: 'DELETE' });
      setRuns((prev) => prev.filter((r) => r._id !== id));
    } catch (err) {
      console.error('Delete failed:', err);
    }
  };

  const hasRunning = runs.some((r) => r.status === 'running' || r.status === 'pending');

  return (
    <div style={{ minHeight: '100vh' }}>
      <Navbar />

      <main className="container" style={{ padding: '2rem 1.5rem' }}>
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <h1 style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '0.25rem' }}>
              ⚡ My Runs
            </h1>
            <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>
              {pagination.total} total runs
              {hasRunning && (
                <span style={{ marginLeft: '0.5rem', color: 'var(--accent-green)', fontWeight: 600 }}>
                  • {runs.filter((r) => r.status === 'running').length} running
                </span>
              )}
            </p>
          </div>

          <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
            {/* Auto-refresh toggle */}
            <button
              className="btn btn-sm"
              style={{
                background: autoRefresh ? 'rgba(16,185,129,0.1)' : 'var(--bg-card)',
                color: autoRefresh ? 'var(--accent-green)' : 'var(--text-secondary)',
                border: autoRefresh ? '1px solid rgba(16,185,129,0.25)' : '1px solid var(--border-subtle)',
              }}
              onClick={() => setAutoRefresh(!autoRefresh)}
            >
              {autoRefresh ? (
                <><span style={{ animation: 'pulse 1.5s infinite', display: 'inline-block' }}>🟢</span> Live</>
              ) : '⏸ Paused'}
            </button>
            <button className="btn btn-primary btn-sm" onClick={() => (window.location.href = '/')}>
              ⚡ New Run
            </button>
          </div>
        </div>

        {/* Status filters */}
        <div style={{ display: 'flex', gap: '0.375rem', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
          {STATUS_FILTERS.map((filter) => (
            <button
              key={filter.id}
              className="btn btn-sm"
              style={{
                background: statusFilter === filter.id ? 'var(--gradient-primary)' : 'var(--bg-card)',
                color: statusFilter === filter.id ? 'white' : 'var(--text-secondary)',
                border: statusFilter === filter.id ? 'none' : '1px solid var(--border-subtle)',
              }}
              onClick={() => setStatusFilter(filter.id)}
            >
              {filter.icon && <span>{filter.icon}</span>}
              {filter.label}
            </button>
          ))}
        </div>

        {/* Runs list */}
        {loading ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {Array.from({ length: 5 }).map((_, i) => (
              <div key={i} className="skeleton" style={{ height: '120px', borderRadius: 'var(--radius-lg)' }} />
            ))}
          </div>
        ) : runs.length === 0 ? (
          <div
            style={{
              textAlign: 'center',
              padding: '5rem 2rem',
              color: 'var(--text-muted)',
            }}
          >
            <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>⚡</div>
            <h3 style={{ fontSize: '1.25rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
              No runs yet
            </h3>
            <p style={{ marginBottom: '1.5rem' }}>
              {statusFilter ? `No ${statusFilter} runs found` : 'Start your first scraper from the Store'}
            </p>
            <button className="btn btn-primary" onClick={() => (window.location.href = '/')}>
              🏪 Browse Scrapers
            </button>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {runs.map((run) => (
              <RunCard
                key={run._id}
                run={run}
                onAbort={handleAbort}
                onDelete={handleDelete}
              />
            ))}
          </div>
        )}

        {/* Pagination */}
        {pagination.totalPages > 1 && (
          <div style={{ display: 'flex', justifyContent: 'center', gap: '0.5rem', marginTop: '2rem' }}>
            <button
              className="btn btn-secondary btn-sm"
              disabled={pagination.page === 1}
              onClick={() => fetchRuns(pagination.page - 1)}
            >
              ← Prev
            </button>
            {Array.from({ length: Math.min(pagination.totalPages, 7) }, (_, i) => i + 1).map((p) => (
              <button
                key={p}
                className="btn btn-sm"
                style={{
                  background: pagination.page === p ? 'var(--gradient-primary)' : 'var(--bg-card)',
                  color: pagination.page === p ? 'white' : 'var(--text-secondary)',
                  border: pagination.page === p ? 'none' : '1px solid var(--border-subtle)',
                  minWidth: '36px',
                }}
                onClick={() => fetchRuns(p)}
              >
                {p}
              </button>
            ))}
            <button
              className="btn btn-secondary btn-sm"
              disabled={pagination.page === pagination.totalPages}
              onClick={() => fetchRuns(pagination.page + 1)}
            >
              Next →
            </button>
          </div>
        )}
      </main>
    </div>
  );
}

// src/app-angular/components/runs/runs.component.ts
import { Component, OnInit, OnDestroy, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';

interface Run {
  _id: string;
  actorId: string;
  actorName: string;
  status: string;
  input?: Record<string, unknown>;
  output?: { resultsCount?: number; previewResults?: unknown[] };
  stats?: { startedAt?: string; finishedAt?: string; durationMs?: number };
  createdAt: string;
}

@Component({
  selector: 'app-runs',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div style="min-height: 100vh;">
      <main class="container" style="padding: 2rem 1.5rem;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
          <div>
            <h1 style="font-size: 1.75rem; font-weight: 800; color: var(--text-primary); margin-bottom: 0.25rem;">
              ⚡ Scraper Run Manager
            </h1>
            <p style="font-size: 0.875rem; color: var(--text-muted);">
              Monitor live scraping execution, view input parameters, inspect output results, or purge runs.
            </p>
          </div>
          <button class="btn btn-secondary btn-sm" (click)="fetchRuns()">🔄 Refresh</button>
        </div>

        <div *ngIf="loading" style="display: flex; flex-direction: column; gap: 1rem;">
          <div *ngFor="let i of [1,2,3]" class="skeleton" style="height: 120px; border-radius: var(--radius-lg);"></div>
        </div>

        <div *ngIf="!loading" style="display: flex; flex-direction: column; gap: 1rem;">
          <div *ngFor="let run of runs" class="card animate-fade-in" style="padding: 1.25rem;">
            <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;">
              <div>
                <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.375rem;">
                  <span [class]="getStatusBadge(run.status)">{{ run.status }}</span>
                  <h3 style="font-size: 1rem; font-weight: 700; color: var(--text-primary); margin: 0;">
                    {{ run.actorName || run.actorId }}
                  </h3>
                </div>
                <div style="font-size: 0.8rem; color: var(--text-muted);">
                  ID: {{ run._id }} &bull; Started: {{ run.createdAt | date: 'medium' }}
                </div>
              </div>

              <div style="display: flex; gap: 0.5rem; align-items: center;">
                <a [href]="'/jobs?runId=' + run._id" class="btn btn-primary btn-sm" style="text-decoration: none;">
                  💼 View Results ({{ run.output?.resultsCount || 0 }})
                </a>
                <button class="btn btn-secondary btn-sm" (click)="toggleDetails(run._id)">
                  👁 Details
                </button>
                <button class="btn btn-ghost btn-sm" (click)="deleteRun(run._id)" style="color: var(--accent-red);">
                  🗑 Delete
                </button>
              </div>
            </div>

            <!-- Details Panel -->
            <div *ngIf="expandedId === run._id" class="animate-fade-in" style="margin-top: 1rem; padding: 1rem; background: var(--bg-secondary); border-radius: var(--radius-md); border: 1px solid var(--border-subtle);">
              <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
                <div>
                  <div style="font-size: 0.75rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase; margin-bottom: 0.375rem;">
                    📥 Input Parameters
                  </div>
                  <pre style="font-size: 0.75rem; color: var(--text-primary); background: var(--bg-card); padding: 0.5rem; border-radius: 6px; overflow: auto; max-height: 150px;">{{ run.input | json }}</pre>
                </div>
                <div>
                  <div style="font-size: 0.75rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase; margin-bottom: 0.375rem;">
                    📤 Output Preview
                  </div>
                  <pre style="font-size: 0.75rem; color: var(--text-primary); background: var(--bg-card); padding: 0.5rem; border-radius: 6px; overflow: auto; max-height: 150px;">{{ run.output | json }}</pre>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  `
})
export class RunsComponent implements OnInit, OnDestroy {
  runs: Run[] = [];
  loading = true;
  expandedId: string | null = null;
  intervalId: any;

  private http = inject(HttpClient);

  ngOnInit() {
    this.fetchRuns();
    this.intervalId = setInterval(() => this.fetchRuns(), 5000);
  }

  ngOnDestroy() {
    if (this.intervalId) clearInterval(this.intervalId);
  }

  fetchRuns() {
    this.http.get<{ runs: Run[] }>('/api/runs').subscribe({
      next: (res) => {
        this.runs = res.runs || [];
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  getStatusBadge(status: string): string {
    if (status === 'succeeded') return 'badge badge-green';
    if (status === 'running') return 'badge badge-orange';
    if (status === 'failed') return 'badge badge-red';
    return 'badge badge-gray';
  }

  toggleDetails(id: string) {
    this.expandedId = this.expandedId === id ? null : id;
  }

  deleteRun(id: string) {
    this.http.delete(`/api/runs/${id}`).subscribe(() => {
      this.fetchRuns();
    });
  }
}
